baseurl = "https://blog.keishasperkins.com/"

title = "KayEssPea Blog"

theme = "ghostwriter"

languageCode = "en-us"

copyright = "Keisha S Perkins"

googleAnalytics = "UA-88471731-1"

disqusShortname = "keishasperkinsblog"

publishDir = "docs"

[Author]

    name = "Keisha S Perkins"

    



[Taxonomies]

    tag = "tags"



[Params]

    intro = true

    headline = "KayEssPea Blog"

    description = "A blog by Keisha S Perkins"

    github = "https://github.com/keishasperkins"

    twitter = "https://twitter.com/keishasperkins"

    email = "ksp@keishasperkins.com"

    opengraph = true

    shareTwitter = true

    shareFacebook = true

    shareGooglePlus = true

    shareLinkedIn = false

    dateFormat = "Mon, Jan 2, 2006"

    highlightJsUrl = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"

    highlightJsLocalUrl = ""



[Permalinks]

    post = "/:year/:month/:day/:filename/"



[[menu.main]]

    name = "Blog Home"

    url = "/"

    weight = 1



[[menu.main]]

    name = "Keishasperkins.com"

    url = "http://keishasperkins.com"

    weight = 2



[[menu.main]]

    name = "Contact"

    url = "/page/contact/"

    weight = 3



[[menu.main]]

    name = "About"

    url = "/page/about/"

    weight = 4